.FF.....FFF
======================================================================
FAIL: test_ignore_directory_no_perm_arg (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '1' != '0'
- 1
+ 0


======================================================================
FAIL: test_ignore_directory_with_perm_arg (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '1' != '0'
- 1
+ 0


======================================================================
FAIL: test_size_some_larger_perms_exact_match (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '2' != '1'
- 2
+ 1


======================================================================
FAIL: test_size_some_larger_perms_no_matches (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '3' != '0'
- 3
+ 0


======================================================================
FAIL: test_size_some_larger_perms_relaxed_match (__main__.TestCountLarge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/stud/cslec/209/marking/grading/a1/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: '4' != '2'
- 4
+ 2


----------------------------------------------------------------------
Ran 11 tests in 0.216s

FAILED (failures=5)
